# Generated by Django 4.2.8 on 2023-12-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_performance_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model',
        ),
    ]
